global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: spark
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:4042"
          - "host.docker.internal:4043"
          - "host.docker.internal:4045"
          - "host.docker.internal:4046"

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:7071"]
